backend = "glx";
vsync = true;
use-damage = true;

blur: {
  method = "dual_kawase";
#BLUR_STRENGTH_START
  strength = 7;
#BLUR_STRENGTH_END
  background = true;
  background-frame = false;
  background-fixed = false;
  blend-color = "#111111";  # Добавьте эту строку для легкого затемнения подложки
}


blur-background-exclude = [
 "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Насильно делаем матрицу и EasyEffects прозрачными для работы блюра
opacity-rule = [
#  "75:class_g = 'Xfce4-terminal' && name = 'cmatrix'",
 # "75:class_g = 'Xfce4-terminal' && name = 'neo-matrix'",
  "70:class_g = 'easyeffects'",
  "100:class_g = 'org.nicotine_plus.Nicotine'",
  "80:class_g = 'i3-frame'",
  "0:x <= -32000",
  "55:class_g = 'tess4d'"
];
corner-radius = 10;    # Радиус скругления в пикселях

# Исключаем i3bar из скругления, чтобы панель оставалась ровной
corner-radius-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'i3-frame'"
];
# Исключения для размытия
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS",
  "x <= -32000"
];
dbus = true;

#fadeing
#fading = true;
# --- Появление окна ---
#fade-in-step = 0.09;    # Меньше = плавнее и дольше появление
# --- Исчезновение окна ---
#fade-out-step = 0.008;   # Меньше = плавнее и дольше исчезновение
#fade-delta = 4;          # Больше = медленнее идёт анимация
#no-fading-openclose = false;

##animation
#animations = (
#  # 1. Анимация появления окна (эффект "вырастания")
#  {
#    triggers = [ "open", "show" ];
#    preset = "appear";
#    scale = 0.8;
#    duration = 0.25;
#  },
#  # 2. Анимация закрытия окна
#  {
#    triggers = [ "close", "hide" ];
#    preset = "disappear";
#    scale = 0.8;
#    duration = 0.2;
#  },
#  # 3. Анимация перетаскивания и изменения размера
#  {
#    triggers = [ "geometry" ];
#    preset = "geometry-change";
#    duration = 0.18;
#  }
#);

animations = (
{
triggers = ["size"];
scale-x = {
curve = "cubic-bezier(0.2, 0, 0.2, 1)";
duration = 0.2;
start = "window-width-before / window-width";
end = 1;
};
scale-y = {
curve = "cubic-bezier(0.2, 0, 0.2, 1)";
duration = 0.2;
start = "window-height-before / window-height";
end = 1;
};
},
{
triggers = ["open", "show"];
opacity = {
curve = "cubic-bezier(0,1,1,1)";
duration = 0.3;
start = 0;
end = "window-raw-opacity";
};
scale-x = {
curve = "cubic-bezier(0,1.3,1,1)";
duration = 0.3;
start = 0.6;
end = 1;
};
scale-y = "scale-x";
offset-x = "(1 - scale-x) / 2 * window-width";
offset-y = "(1 - scale-y) / 2 * window-height";
},
{
triggers = ["close", "hide"];
opacity = {
curve = "cubic-bezier(0,1,1,1)";
duration = 0.2;
start = "window-raw-opacity-before";
end = 0;
};
scale-x = {
curve = "cubic-bezier(0,1.3,1,1)";
duration = 0.2;
start = 1;
end = 0.8;
};
scale-y = "scale-x";
offset-x = "(1 - scale-x) / 2 * window-width";
offset-y = "(1 - scale-y) / 2 * window-height";
}
)
