bind_to_address "localhost"
audio_output {
        type            "pulse"
        name            "PipeWire Sound Server"
}
music_directory    "/home/rysia/Music/"
audio_output {
    type            "fifo"
    name            "Visualizer"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
playlist_directory "~/.config/mpd/playlists"
state_file         "~/.config/mpd/state"

