
[colors]

background = #282a36

background-alt = #44475a

foreground = #f8f8f2

primary = #bd93f9

secondary = #8be9fd

alert = #ff5555

disabled = #6c7086



[bar/main]

# Возвращаем стандартный режим (никаких скрытых слоев и уходов под окна)

override-redirect = false

fixed-center = true



# Делаем ширину 100%, но сжимаем сам бар за счет прозрачных рамок!

width = 100%

height = 24pt

radius = 10



# ФОКУС: Добавляем рамки. Цвет #00000000 — это абсолютная прозрачность.

# Боковые рамки по 1% (или в пикселях, например 15pt) создадут эффект ширины 98%

border-left-size = 6pt

border-right-size = 6pt

border-top-size = 3pt

border-color = #00000000



# Сохраняем вашу прозрачность для красивого блюра (ARGB)

background = #dd282a36

foreground = ${colors.foreground}



# Визуальные отступы внутри самого бара

line-size = 3pt

padding-left = 2

padding-right = 2

module-margin = 1



# Разделитель модулей

separator = "\"

separator-foreground = ${colors.disabled}



# Шрифты

font-0 = "JetBrainsMono Nerd Font:size=10;2"

font-1 = "Symbols Nerd Font:size=12;3"

font-2 = "Font Awesome 6 Free Solid:size=10;2"



# Порядок модулей

modules-left = xworkspaces

modules-center = xwindow

modules-right = pulseaudio xkeyboard memory cpu battery0 battery1 date systray



cursor-click = pointer

cursor-scroll = ns-resize

enable-ipc = true



[module/xworkspaces]

type = internal/xworkspaces

label-active = %name%

label-active-background = ${colors.background-alt}

label-active-underline= ${colors.primary}

label-active-padding = 2



label-occupied = %name%

label-occupied-padding = 1



label-urgent = %name%

label-urgent-background = ${colors.alert}

label-urgent-padding = 1



label-empty = %name%

label-empty-foreground = ${colors.disabled}

label-empty-padding = 1



[module/xwindow]

type = internal/xwindow

label = %title:0:40:...%

label-foreground = #ffffff
#label-foreground = #708de7
#label-foreground = #6789f1

[module/pulseaudio]

type = internal/pulseaudio

format-volume = <label-volume>

#format-volume-prefix = "🔊 "

format-volume-prefix-foreground = ${colors.primary}

label-volume = %percentage%%



format-muted = <label-muted>

format-muted-prefix = "🔇 "

format-muted-prefix-foreground = ${colors.disabled}

label-muted = muted

label-muted-foreground = ${colors.disabled}



[module/xkeyboard]

type = internal/xkeyboard

blacklist-0 = num lock

blacklist-1 = scroll lock

format-prefix = "󰌌 "

format-prefix-foreground = ${colors.secondary}

label-layout = %layout%

label-layout-transform = uppercase



[module/memory]

type = internal/memory

interval = 2

format-prefix = "󰍛 "

format-prefix-foreground = ${colors.primary}

label = %percentage_used%%



#[module/cpu]

#type = internal/cpu

#interval = 2

#format-prefix = "󰻠 "

#format-prefix-foreground = ${colors.secondary}

#label = %percentage%%

[module/cpu]
type = custom/ipc
# hook-0: Выводит процент загрузки (берем из /proc/loadavg или через быстрый awk)
hook-0 = grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%.0f%%\n", usage}'
# hook-1: Выводит температуру процессора
hook-1 = sensors | grep 'Core 0' | awk '{print $3}'
initial = 1
format-prefix = "󰻠 "
format-prefix-foreground = ${colors.secondary}
click-left = "#cpu.next"

# Внутренняя батарея T450s (BAT0)

[module/battery0]

type = internal/battery

battery = BAT0

adapter = AC

full-at = 98



format-charging = <label-charging>

#format-charging-prefix = "⚡ B0 "

format-charging-prefix-foreground = #50fa7b



format-discharging = <label-discharging>

#format-discharging-prefix = "🔋 B0 "

format-discharging-prefix-foreground = ${colors.secondary}



label-charging = %percentage%%

label-discharging = %percentage%%

#label-full = "🔋 B0 100%"

label-full-foreground = ${colors.disabled}



# Внешняя батарея T450s (BAT1)

[module/battery1]

type = internal/battery

battery = BAT1

adapter = AC

full-at = 98



format-charging = <label-charging>

#format-charging-prefix = "⚡ B1 "

format-charging-prefix-foreground = #50fa7b



format-discharging = <label-discharging>

#format-discharging-prefix = "🔋 B1 "

format-discharging-prefix-foreground = ${colors.secondary}



label-charging = %percentage%%

label-discharging = %percentage%%

#label-full = "🔋 B1 100%"

label-full-foreground = ${colors.disabled}



[module/date]

type = internal/date

interval = 1

date = "󰥔 %H:%M"

date-alt = "󰃭 %Y-%m-%d %H:%M:%S"

label = %date%

label-foreground = ${colors.primary}



[settings]

screenchange-reload = true

pseudo-transparency = true



[module/systray]

type = internal/tray

format-margin = 4pt

tray-spacing = 6pt

tray-size = 14pt 

